### ISSUE TITLE
Captilization error

### ISSUE THREAD

**Issue by tuyyui** [ColinTheShark/DiceBot#1]
the imports for Emoji, Message, and Filters should be lowercased to emoji, message, and filters

**Comment by ColinShark** [comment]
The latest commit was back in April and I have yet to make literally any effort to updating to Pyrogram v1.x.
Since Telegram implemented their 🎲 Dice animated Emoji to roll a d6 this project became somewhat useless and anyone who wants to can fork and update their own version.
